### ISSUE TITLE
Can't get past the welcome screen on some devices

### ISSUE THREAD

**Issue by arift** [arift/booleYou-client#47]
On certain devices (only Nexus 6 as of writing this), the buttons for login and signup on the welcome screen are unresponsive. Because of this, you can not get past the welcome screen. 
So far the cause is unknown.

**Comment by huygaa11** [comment]
how is it going?

**Comment by stanleyrya** [comment]
Going to ignore it until after presentation, then the plan is to look into getting logcat statements into the apk

**Comment by michaelrabie** [comment]
It works for me with phonegap and the apk.

**Comment by jtyler92** [comment]
Is this still an issue? Can we close it?

**Comment by stanleyrya** [comment]
I don't believe anyone looked into this yet

**Comment by stanleyrya** [comment]
http://robandlauren.com/2014/01/16/console-logging-phonegap/

This could be very useful. Arif, can you still repeat the error?

**Comment by stanleyrya** [comment]
Regardless we should add this in for future use. Couldn't hurt

**Comment by arift** [comment]
The issue still exists on my phone. Will take a look at this

**Comment by ianfox1992** [comment]
Any updates on this issue? Are we officially dropping support of Nexus phone?

**Comment by arift** [comment]
It's been resolved.
