### ISSUE TITLE
The welcome screen does not show some UI elements without scrolling down.

### ISSUE THREAD

**Issue by Humdilla** [arift/booleYou-client#57]
The "Sign Up" and "Log In" buttons are not immediately visible when navigating to the welcome screen on a PC. In order to see them, you must scroll down. It took me quite a bit of time to figure out how to sign up when I first tried to use the site.

Tested on firefox and chromium ubuntu 14.04

**Comment by arift** [comment]
This issue is now fixed. Closing.
