### ISSUE TITLE
Drag refresh functionality is not working

### ISSUE THREAD

**Issue by Humdilla** [arift/booleYou-client#63]
Dragging the screen down when at the top of the booleFeed does not refresh my feed.
Tested on firefox and chromium ubuntu 14.04

**Comment by dansaunders200713** [comment]
I haven't been able to duplicate this in any browser or phone. Anyone?

**Comment by ianfox1992** [comment]
I have also been unable to replicate this on the browser version using both chrome and firefox, closing
