### ISSUE TITLE
Auto filling comment field with previous comment makes it super easy to spam

### ISSUE THREAD

**Issue by prfarlow1** [arift/booleYou-client#64]
Testing on a Galaxy S3, I was able to easy spam all of the top posts very easily. Not only does this make spamming easy, but if you ever introduce metrics about posts, this could allow users to manipulate them. I would recommend taking away this feature.

**Comment by prfarlow1** [comment]
Here's an example:

![2015-04-14 22 10 17](https://cloud.githubusercontent.com/assets/6036075/7151153/ce71c204-e2f3-11e4-906f-8bbeacb30d5d.png)

I had previously commented 'please' on a post and so the next time I go to comment on any post, 'please' is auto-filed in. This makes it incredible easy to post a large number of booleOuts in a short time frame, because it only requires 2 button presses to repeat the same comment over and over again.

**Comment by huygaa11** [comment]
I believe it got solved?

**Comment by dansaunders200713** [comment]
this issue has been resolved. the text in the reply field is erased after the reply is posted.
