### ISSUE TITLE
Correct user data not being shown in profile

### ISSUE THREAD

**Issue by Humdilla** [arift/booleYou-client#65]
The user data that shows up in my profile is not correct.
Tested on firefox and chromium ubuntu 14.04
![selection_003](https://cloud.githubusercontent.com/assets/652215/7121765/bffaced8-e1e4-11e4-8d2a-d2680524d028.png)

**Comment by dansaunders200713** [comment]
This issue occurs when you reload booleYou on your browser, and does not occur on phones because it is not possible to "refresh" the app. Browser not explicitly supported for the application.
