### ISSUE TITLE
Can't create password.

### ISSUE THREAD

**Issue by dpharris12** [arift/booleYou-client#66]
When creating an account, if you click the password field and start to type, it removes the cursor from the field and Password is written in bold. You are then unable to click back into the password field. This was done on Chrome on a laptop.

**Comment by dansaunders200713** [comment]
As far as I know, we haven't been able to duplicate this bug. Anyone?

**Comment by ianfox1992** [comment]
I just tried on the desktop version and could not replicate, closing
