### ISSUE TITLE
Touchscreen computer scrolling

### ISSUE THREAD

**Issue by RConnell425** [arift/booleYou-client#67]
When using a touchscreen, the only option for scrolling is to use the touchscreen. Two finger scrolling, dragging the screen, using the arrow keys, etc. don't seem to work.

Also, the app has to be the only tab open in the window in order for the touchscreen dragging to work. Otherwise, you are out of luck.

**Comment by arift** [comment]
The app is meant to be used on touch-enabled mobile devices. It's not meant to run in a browser. Browser experience is generally poor and is only for quick demos and testing. Ionic has limited keyboard/mouse support.
