### ISSUE TITLE
UI is inconsistant across mobile devices

### ISSUE THREAD

**Issue by gmarkv10** [arift/booleYou-client#69]
When using a Windows phone and the user tries to make a post, the text input bar is long enough that is pushes the '1' and '0' box' off the right of the screen.  The user can press the edge of  the screen repeatedly and eventually a 1 will appear but if I didn't know that's where the button is, I might not have been able to even figure that out
![bug](http://imgur.com/qf8Vcny.jpg)

Device used:  Nokia Lumia 1020

**Comment by arift** [comment]
Windows Phone is not supported.

**Comment by gmarkv10** [comment]
0 #booleyou

**Comment by stanleyrya** [comment]
"0 #booleyou" is not a supported boolOut.

**Comment by gmarkv10** [comment]
is it a supported github comment?
